/**
 * Emits the C view of the frame schema from the TypeScript source of truth.
 *
 * Scope is deliberately narrow (risk R0.6): constants, enums, the header struct,
 * compile-time assertions and the byte-order accessors. No template engine, no
 * plugin surface, no user-supplied formatting. If this file starts to look like
 * a framework, it has gone wrong.
 *
 * Determinism is a hard requirement (risk R0.4). The output embeds a hash of the
 * schema and nothing else — no timestamp, no path, no toolchain version — so
 * regenerating an unchanged schema produces a byte-identical file and `--check`
 * stays quiet. A generator that emits a fresh diff on every run trains people to
 * ignore the drift gate, which is worse than having no gate.
 */
import { createHash } from 'node:crypto';
import {
  BRIDGE_ID,
  BROADCAST_ID,
  CRC_SIZE,
  FRAME_MAGIC,
  FrameFlags,
  FrameType,
  HEADER_LAYOUT,
  HEADER_SIZE,
  LORA_MTU,
  MAX_PAYLOAD,
  MIN_FRAME_SIZE,
  type HeaderEndian,
} from '../frame.js';

const C_TYPE_FOR: Record<HeaderEndian, string> = {
  u8: 'uint8_t',
  be16: 'uint16_t',
};

/** Numeric members of a TS numeric enum, in declaration order. */
function enumMembers(e: Record<string, string | number>): { name: string; value: number }[] {
  return Object.entries(e)
    .filter((entry): entry is [string, number] => typeof entry[1] === 'number')
    .map(([name, value]) => ({ name, value }));
}

const hex = (value: number, width: number): string =>
  `0x${value.toString(16).toUpperCase().padStart(width, '0')}`;

/**
 * Canonical description of everything the generated header depends on.
 *
 * The hash is taken over this, so any schema change moves the hash and any
 * change that does not touch the schema leaves it alone.
 */
function schemaFingerprint(): string {
  const canonical = JSON.stringify({
    magic: FRAME_MAGIC,
    headerSize: HEADER_SIZE,
    crcSize: CRC_SIZE,
    loraMtu: LORA_MTU,
    maxPayload: MAX_PAYLOAD,
    minFrameSize: MIN_FRAME_SIZE,
    broadcastId: BROADCAST_ID,
    bridgeId: BRIDGE_ID,
    layout: HEADER_LAYOUT.map((f) => [f.name, f.offset, f.size, f.endian]),
    types: enumMembers(FrameType).map((m) => [m.name, m.value]),
    flags: enumMembers(FrameFlags).map((m) => [m.name, m.value]),
  });
  return createHash('sha256').update(canonical).digest('hex').slice(0, 8);
}

export function emitCHeader(): string {
  const lines: string[] = [];
  const asserts: string[] = [];
  const put = (line = ''): number => lines.push(line);
  const staticAssert = (expr: string, message: string): void => {
    asserts.push(`_Static_assert(${expr}, "${message}");`);
  };

  put('/* AUTO-GENERATED by packages/protocol — DO NOT EDIT.');
  put(' *');
  put(' * Source of truth: packages/protocol/src/frame.ts (HEADER_LAYOUT).');
  put(' * Regenerate with `pnpm gen:c`; CI runs `pnpm gen:c --check` and fails on');
  put(' * any hand edit. Change the schema, not this file.');
  put(' *');
  put(` * source-hash: ${schemaFingerprint()}`);
  put(' */');
  put('#pragma once');
  put();
  put('#include <stdint.h>');
  put('#include <stddef.h>');
  put('#include <assert.h>');
  put();
  put('#ifdef __cplusplus');
  put('extern "C" {');
  put('#endif');
  put();

  put('/* ---- Frame geometry ---------------------------------------------------- */');
  put(`#define LH_FRAME_MAGIC     ${hex(FRAME_MAGIC, 2)}u`);
  put(`#define LH_HEADER_SIZE     ${HEADER_SIZE}u`);
  put(`#define LH_CRC_SIZE        ${CRC_SIZE}u`);
  put(`#define LH_LORA_MTU        ${LORA_MTU}u`);
  put(`#define LH_MAX_PAYLOAD     ${MAX_PAYLOAD}u`);
  put(`#define LH_MIN_FRAME_SIZE  ${MIN_FRAME_SIZE}u`);
  put(`#define LH_BROADCAST_ID    ${hex(BROADCAST_ID, 4)}u`);
  put(`#define LH_BRIDGE_ID       ${hex(BRIDGE_ID, 4)}u  /* the Bridge itself; never on air */`);
  put();

  staticAssert(
    'LH_BRIDGE_ID != LH_BROADCAST_ID',
    'the bridge-local address must not collide with broadcast',
  );

  staticAssert(
    'LH_MAX_PAYLOAD == LH_LORA_MTU - LH_HEADER_SIZE - LH_CRC_SIZE',
    'MAX_PAYLOAD is not derivable from MTU/header/CRC',
  );
  staticAssert(
    'LH_MIN_FRAME_SIZE == LH_HEADER_SIZE + LH_CRC_SIZE',
    'MIN_FRAME_SIZE is not header + CRC',
  );

  put('/* ---- Field offsets (wire order) ---------------------------------------- */');
  for (const field of HEADER_LAYOUT) {
    const name = field.name.toUpperCase();
    put(`#define LH_HDR_OFF_${name.padEnd(10)} ${field.offset}u`);
    put(`#define LH_HDR_LEN_${name.padEnd(10)} ${field.size}u`);
  }
  put();

  put('/* ---- Frame types ------------------------------------------------------- */');
  put('typedef enum {');
  for (const { name, value } of enumMembers(FrameType)) {
    put(`    LH_TYPE_${name.padEnd(16)} = ${hex(value, 2)},`);
  }
  put('} lh_frame_type_t;');
  put();

  put('/* ---- Frame flags ------------------------------------------------------- */');
  put('typedef enum {');
  for (const { name, value } of enumMembers(FrameFlags)) {
    put(`    LH_FLAG_${name.padEnd(16)} = ${hex(value, 2)},`);
  }
  put('} lh_frame_flags_t;');
  put();

  put('/* ---- Header struct ------------------------------------------------------');
  put(' * `packed` plus the assertions below are belt and braces: we do not trust');
  put(' * any toolchain not to insert padding, we verify it at compile time on');
  put(' * every target (risk R0.1).');
  put(' */');
  put('typedef struct __attribute__((packed)) {');
  for (const field of HEADER_LAYOUT) {
    const cType = C_TYPE_FOR[field.endian];
    const note = field.endian === 'be16' ? '  /* big-endian on wire — use accessor */' : '';
    put(`    ${cType.padEnd(9)} ${field.name};${note}`);
  }
  put('} lh_header_t;');
  put();

  staticAssert('sizeof(lh_header_t) == LH_HEADER_SIZE', 'header size drift');
  for (const field of HEADER_LAYOUT) {
    staticAssert(
      `offsetof(lh_header_t, ${field.name}) == LH_HDR_OFF_${field.name.toUpperCase()}`,
      `${field.name} offset drift`,
    );
    staticAssert(
      `sizeof(((lh_header_t *)0)->${field.name}) == LH_HDR_LEN_${field.name.toUpperCase()}`,
      `${field.name} width drift`,
    );
  }

  put('/* ---- Compile-time contract ---------------------------------------------- */');
  for (const line of asserts) put(line);
  put();

  put('/* ---- Byte-order accessors ------------------------------------------------');
  put(' * Multi-byte fields are big-endian on the wire; every device we ship on is');
  put(' * little-endian. Reading hdr->src_id directly returns a byte-swapped value');
  put(' * that still looks plausible, which is risk R0.2. These read the raw bytes');
  put(' * at the schema offset, so they are correct on either host endianness.');
  put(' */');
  for (const field of HEADER_LAYOUT) {
    if (field.endian !== 'be16') continue;
    const off = `LH_HDR_OFF_${field.name.toUpperCase()}`;
    put(`static inline uint16_t lh_hdr_get_${field.name}(const lh_header_t *hdr) {`);
    put('    const uint8_t *raw = (const uint8_t *)hdr;');
    put(`    return (uint16_t)(((uint16_t)raw[${off}] << 8) | (uint16_t)raw[${off} + 1u]);`);
    put('}');
    put();
    put(`static inline void lh_hdr_set_${field.name}(lh_header_t *hdr, uint16_t value) {`);
    put('    uint8_t *raw = (uint8_t *)hdr;');
    put(`    raw[${off}]      = (uint8_t)(value >> 8);`);
    put(`    raw[${off} + 1u] = (uint8_t)(value & 0xFFu);`);
    put('}');
    put();
  }

  put('#ifdef __cplusplus');
  put('}');
  put('#endif');

  // Trailing newline, LF endings: the file is compared byte-for-byte by
  // `--check`, so line endings must not depend on the platform that ran it.
  return lines.join('\n') + '\n';
}

export function generatedHeaderHash(): string {
  return schemaFingerprint();
}

/** Number of `_Static_assert`s in the emitted header — tracked as a metric. */
export function countStaticAsserts(source: string): number {
  return source.split('\n').filter((line) => line.startsWith('_Static_assert(')).length;
}
